name: hedgelog
description: An app for keeping track of hedgehog care

dependencies:
  intl: ^0.15.6
  rxdart: ^0.16.7
  cloud_firestore: ^0.9.7
  firebase_messaging: ^4.0.0+1
  firebase_auth: ^0.8.2
  google_sign_in: ^4.0.1+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family:  HedgelogIcons
      fonts:
        - asset: fonts/HedgelogIcons.ttf
