name: hedgelog
description: An app for keeping track of hedgehog care

dependencies:
  intl: ^0.15.6
  rxdart: ^0.16.7
  cloud_firestore: ^0.7.0
  firebase_messaging: ^1.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family:  HedgelogIcons
      fonts:
        - asset: fonts/HedgelogIcons.ttf
