/// Flutter icons HedgelogIcons
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HedgelogIcons
///      fonts:
///       - asset: fonts/HedgelogIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HedgelogIcons
///      fonts:
///       - asset: fonts/HedgelogIcons.ttf
///
///
///


/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HedgelogIcons
///      fonts:
///       - asset: fonts/HedgelogIcons.ttf
///
///
///

class HedgelogIcons {
  HedgelogIcons._();

  static const _FontFam = 'HedgelogIcons';

  static const IconData hedgehog =
  const IconData(0xe800, fontFamily: _FontFam);
  static const IconData thermometer_up =
  const IconData(0xe801, fontFamily: _FontFam);
  static const IconData thermometer_down =
  const IconData(0xe802, fontFamily: _FontFam);
  static const IconData thermometer =
  const IconData(0xe803, fontFamily: _FontFam);
}
